name: j4rs CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and Test Java with Maven
        run: mvn -f ./java/pom.xml --batch-mode --update-snapshots install
      - name: Build and Test the JavaFX module with Maven
        run: mvn -f ./java/pom.xml --batch-mode --update-snapshots install
      - name: Build and install Java testing resources with Maven
        run: mvn -f ./test-resources/java/pom.xml --batch-mode --update-snapshots install
      - name: Build Rust with Cargo
        run: cargo build --manifest-path ./rust/Cargo.toml --verbose
      - name: Test Rust with Cargo
        run: cargo test --manifest-path ./rust/Cargo.toml --verbose